server:
  port: 30000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/result
    min-response-size: 1024
  tomcat:
    min-spare-threads: 10
    accept-count: 600
    max-threads: 800

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stock
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true