server:
  port: 30000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/result
    min-response-size: 1024
  tomcat:
    min-spare-threads: 10
    accept-count: 600
    max-threads: 800

spring:
  profiles.active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/stock?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true


# Elasticsearch Config
elasticsearch:
  # host ip1,ip2,,,
  host: {ES_HOST}
  port: 9300
  clusterName: elasticsearch
  clientTransportSniff: false